version: 0.2

phases:
  install:
    commands:
      - echo Running an install
  pre_build:
    commands:
      - echo Running a pre_build
  build:
    commands:
      - echo Running a build
  post_build:
    commands:
      - echo Running a post_build
